table QueryExecutions
	lineageTag: 44807d1c-9eb5-4e9d-abd2-8a552e53cdcd

	/// Number of query executions in the current filter context.
	measure 'Total Executions' = COUNTROWS(QueryExecutions)
		formatString: #,0
		lineageTag: 085415fa-28be-4825-8146-a5607f6576e6

	measure 'Successful Executions' = CALCULATE([Total Executions], QueryExecutions[Outcome] = "Success")
		formatString: #,0
		lineageTag: 1835a92e-c06e-4ba6-a5d4-79a462736891

	measure 'Failed Executions' = CALCULATE([Total Executions], QueryExecutions[Outcome] = "Error")
		formatString: #,0
		lineageTag: 6d8e1a86-d187-4893-97cc-94f2470fa9b7

	/// Queries per second — successful executions divided by run duration. Within a single run this matches the headline QPS reported by the load generator.
	measure QPS = DIVIDE([Successful Executions], MAX(LoadTestRuns[DurationSec]))
		formatString: 0.0
		lineageTag: d361b3d5-6d38-478c-9f71-c3b31f4ef3a6

	/// Mean client-observed query duration in milliseconds.
	measure 'Avg Latency (ms)' = AVERAGE(QueryExecutions[ClientDurationMs])
		formatString: #,0
		lineageTag: 0ea1f035-87da-48d5-98f2-ba785052e43c

	measure 'Max Latency (ms)' = MAX(QueryExecutions[ClientDurationMs])
		formatString: #,0
		lineageTag: 467db6b0-348a-4028-af97-7f841e4c65d2

	measure 'P50 Latency (ms)' = PERCENTILEX.INC(QueryExecutions, QueryExecutions[ClientDurationMs], 0.5)
		formatString: #,0
		lineageTag: 3cfae3e2-4c8d-488f-aa40-79927a30a46e

	measure 'P95 Latency (ms)' = PERCENTILEX.INC(QueryExecutions, QueryExecutions[ClientDurationMs], 0.95)
		formatString: #,0
		lineageTag: 576a3f1e-a664-4201-acbf-f3f89741d657

	measure 'P99 Latency (ms)' = PERCENTILEX.INC(QueryExecutions, QueryExecutions[ClientDurationMs], 0.99)
		formatString: #,0
		lineageTag: 914e1f9c-4c0a-4fbf-9469-4e46dbc5b76e

	/// Total engine CPU consumed, in CPU-seconds. Sum of ExecutionMetrics.totalCpuTimeMs across executions.
	measure 'Engine CPU (s)' = DIVIDE(SUM(QueryExecutions[EngineCpuMs]), 1000)
		formatString: 0.00
		lineageTag: 6b1db459-8e5a-4d8d-b333-0a9ed9d6ac65

	measure 'SE CPU (s)' = DIVIDE(SUM(QueryExecutions[SECpuMs]), 1000)
		formatString: 0.00
		lineageTag: 84f746ff-4ad9-4973-8d51-a1e85ac28b64

	measure 'FE CPU (s)' = DIVIDE(SUM(QueryExecutions[FECpuMs]), 1000)
		formatString: 0.00
		lineageTag: 831e1dbb-a89d-4275-a968-95c97bada0ea

	measure 'Engine Duration (s)' = DIVIDE(SUM(QueryExecutions[EngineDurationMs]), 1000)
		formatString: 0.00
		lineageTag: 4242d79e-269b-47b7-94a2-9a8e4028982a

	/// Total engine CPU in milliseconds. Used as the ranking measure for the Top Queries by CPU visual.
	measure 'Total Engine CPU (ms)' = SUM(QueryExecutions[EngineCpuMs])
		formatString: #,0
		lineageTag: 82947d8f-c861-4f16-b24d-f700909e16ab

	/// Peak concurrent virtual users seen at any point in the current filter context.
	measure 'Active Users (max)' = MAX(QueryExecutions[ActiveUsersAtStart])
		formatString: #,0
		lineageTag: 016ca1de-f0fc-49e4-b5f9-9e26cbe226a1

	/// Total capacity-router throttling time, in seconds. Sum of ExecutionMetrics.capacityThrottlingMs across executions. >0 indicates the capacity SKU was throttling.
	measure 'Throttling (s)' = DIVIDE(SUM(QueryExecutions[CapacityThrottlingMs]), 1000)
		formatString: 0.00
		lineageTag: 8a4c1d72-1a3e-4e7b-a2cb-7f4e6b9c1d22

	measure 'Throttled Executions' = CALCULATE([Total Executions], QueryExecutions[CapacityThrottlingMs] > 0)
		formatString: #,0
		lineageTag: c14a92d5-2d8b-4f1a-9b0a-6d3a8e4f1c33

	/// Fraction of executions that were capacity-router throttled.
	measure '% Throttled' = DIVIDE([Throttled Executions], [Total Executions])
		formatString: 0.0%
		lineageTag: 9b1e7c38-3f4d-45a2-bb71-1f2a9d0e7c44


	column Source
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: c9a0fb3c-5115-4fd5-bde9-7a4d4989e5a7
		summarizeBy: none
		sourceColumn: Source

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SourceId
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: 54f3e1d1-0c30-42df-ad29-119775a58b2c
		summarizeBy: none
		sourceColumn: SourceId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LoadTestId
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: 6621fcf1-967a-4ff6-95ae-6677921e6c42
		summarizeBy: none
		sourceColumn: LoadTestId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserIndex
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b71d5c60-96ab-4879-b1d6-9449fff4b05c
		summarizeBy: none
		sourceColumn: UserIndex

		annotation SummarizationSetBy = Automatic

	column UserEmail
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4b9962fd-610e-41de-9041-bc8f91833c12
		summarizeBy: none
		sourceColumn: UserEmail

		annotation SummarizationSetBy = Automatic

	column QueryIndex
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: int
		lineageTag: a6006bf5-d5b0-4363-950c-94a67d4e7155
		summarizeBy: none
		sourceColumn: QueryIndex

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QueryHash
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7e22b95c-86f2-4907-8314-12dca0cacd34
		summarizeBy: none
		sourceColumn: QueryHash

		annotation SummarizationSetBy = Automatic

	column Iteration
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: int
		lineageTag: 472a4752-a009-4d79-ad3d-5ab1b3e51345
		summarizeBy: sum
		sourceColumn: Iteration

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QuerySeq
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: int
		lineageTag: c55e06cf-d7fe-4a6b-a477-cf66fd970fa2
		summarizeBy: none
		sourceColumn: QuerySeq

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RequestId
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: 813814bd-f3ec-43f1-a6f8-65dd357f02a4
		summarizeBy: none
		sourceColumn: RequestId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LogicalSessionId
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: 88147c64-78b9-4ddd-8771-522627ff55e5
		summarizeBy: none
		sourceColumn: LogicalSessionId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StartUtc
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: d3af3658-b661-46a1-a811-f36e459045e5
		summarizeBy: none
		sourceColumn: StartUtc

		annotation SummarizationSetBy = Automatic

	column EndUtc
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 0318f21d-ec0c-46e8-bf09-24b4ed3bbb65
		summarizeBy: none
		sourceColumn: EndUtc

		annotation SummarizationSetBy = Automatic

	column StartTimeMs
		dataType: double
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: float
		lineageTag: 7359c076-5f5e-47a0-8642-6548c2d65152
		summarizeBy: sum
		sourceColumn: StartTimeMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientDurationMs
		dataType: double
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: float
		lineageTag: 170ea6bd-2819-41f4-9f8d-2f6d7f4e6629
		summarizeBy: sum
		sourceColumn: ClientDurationMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EngineDurationMs
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 8a4ecf33-262c-41f7-9e0d-3287a4e80f17
		summarizeBy: sum
		sourceColumn: EngineDurationMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EngineCpuMs
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 607b33cc-8fc5-4a06-adb4-8be764f08f25
		summarizeBy: sum
		sourceColumn: EngineCpuMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SECpuMs
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: cec1f335-92b8-42c5-9285-7a2fbe64e8bd
		summarizeBy: sum
		sourceColumn: SECpuMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FECpuMs
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: e3482d54-3a9b-4924-91b0-4fb00aa67246
		summarizeBy: sum
		sourceColumn: FECpuMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ExecutionDelayMs
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ed666e26-9354-4513-86eb-c5d45e1d9051
		summarizeBy: sum
		sourceColumn: ExecutionDelayMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CapacityThrottlingMs
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 5d6e3a14-7c1c-4a72-9b7a-9e1c4b8c2d11
		summarizeBy: sum
		sourceColumn: CapacityThrottlingMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PeakMemoryKB
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 1ca5d470-ecbf-493e-a967-6d4d25349aaf
		summarizeBy: sum
		sourceColumn: PeakMemoryKB

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QueryResultRows
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 5c66ec1d-5102-4ad7-9ce2-ec66a6daff3c
		summarizeBy: sum
		sourceColumn: QueryResultRows

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ExecutionMetricsJson
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: varchar(8000)
		lineageTag: b6dbd370-e253-499d-b929-d14aa8951e02
		summarizeBy: none
		sourceColumn: ExecutionMetricsJson

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VertiPaqQueryCount
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: int
		lineageTag: 9350fe05-32f6-4813-96b1-b2982b373bb7
		summarizeBy: sum
		sourceColumn: VertiPaqQueryCount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VertiPaqDurationMs
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 33e41f9a-b03f-401c-a85a-b598ae52b040
		summarizeBy: sum
		sourceColumn: VertiPaqDurationMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DirectQueryCount
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: int
		lineageTag: d26b81b8-268f-4011-a2fe-35132ae7e591
		summarizeBy: sum
		sourceColumn: DirectQueryCount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DirectQueryDurationMs
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: fb404955-e362-4822-a587-a1e137ae0331
		summarizeBy: sum
		sourceColumn: DirectQueryDurationMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DirectQueryCpuMs
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 75b45da4-cfe6-4324-9640-9b7c6c8db07e
		summarizeBy: sum
		sourceColumn: DirectQueryCpuMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Outcome
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: dbe7c03a-ce11-4d26-9202-1caec51684d5
		summarizeBy: none
		sourceColumn: Outcome

		annotation SummarizationSetBy = Automatic

	column RowCount
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: int
		lineageTag: 40601e56-61ae-4e1b-9f42-74d993b5f583
		summarizeBy: sum
		sourceColumn: RowCount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ResponseBytes
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: bigint
		lineageTag: f1507659-981e-462f-893f-5002e2cd5ae4
		summarizeBy: sum
		sourceColumn: ResponseBytes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ErrorMessage
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 244ad96c-010e-4f41-84e7-ed02b78a44e3
		summarizeBy: none
		sourceColumn: ErrorMessage

		annotation SummarizationSetBy = Automatic

	column ActiveUsersAtStart
		dataType: int64
		isHidden
		isAvailableInMdx: false
		formatString: 0
		sourceProviderType: int
		lineageTag: 13ca974c-7205-436b-88b3-d34f9e32ac3b
		summarizeBy: max
		sourceColumn: ActiveUsersAtStart

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RunQueryKey = QueryExecutions[SourceId] & "|" & QueryExecutions[QueryHash]
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 65e301ba-912a-4bcd-b8ff-4411718fc082
		summarizeBy: none

	column StartSecond = INT(QueryExecutions[StartTimeMs] / 1000)
		dataType: int64
		formatString: 0
		lineageTag: e9186c6c-8fb9-423b-ad4e-7094f91bad84
		summarizeBy: none


	partition QueryExecutions = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database(ServerName, DatabaseName),
				    Data = Source{[Schema=SchemaName, Item="QueryExecutions"]}[Data]
				in
				    Data

	annotation PBI_ResultType = Table
